function Calculadora() {
	var cero = document.getElementById('0')
	var uno = document.getElementById('1')
	var dos = document.getElementById('2')
	var tres = document.getElementById('3')
	var cuatro = document.getElementById('4')
	var cinco = document.getElementById('5')
	var seis = document.getElementById('6')
	var siete = document.getElementById('7')
	var ocho = document.getElementById('8')
	var nueve = document.getElementById('9')
	var sumar = document.getElementById('mas')
	var restar = document.getElementById('menos')
	var multiplicar = document.getElementById('por')
	var dividir = document.getElementById('dividido')
	var resultado = document.getElementById('igual')
	var punto = document.getElementById('punto')
	var onc = document.getElementById('on')
	var signo = document.getElementById('sign')
}